name: day20_quality_monitoring
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - sentence-transformers>=2.7.0
      - torch>=2.2.0
      - openai>=1.40.0
      - google-generativeai>=0.7.0
      - python-dotenv>=1.0.1
