name: day07_web_rag_mini
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - fastapi
      - uvicorn[standard]
      - python-dotenv
      - openai>=1.0.0
      - faiss-cpu
      - numpy
      - httpx
