name: day22_model_registry
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - fastapi==0.115.0
      - uvicorn==0.30.6
      - sqlalchemy==2.0.35
      - pydantic==1.10.17
      - pytest==8.3.3
      - httpx==0.27.2
      - pytest-asyncio
